# To use the workflow, make sure you have completed the following steps in repository settings:
#   1. Create a ruleset for 'main' branch: status check 'merge' is required.
#   2. Enable 'Allow auto-merge' in 'General'.
# Without above steps, the workflow enables Dependabot pull requests to be merged unconditionally.

name: Dependabot auto-merge
# Uncomment the next line to enable the workflow.
# on: pull_request

permissions:
  contents: write

jobs:
  dependabot:
    runs-on: ubuntu-latest
    if: github.event.pull_request.user.login == 'dependabot[bot]'
    steps:
      - name: Enable auto-merge for Dependabot PRs
        run: gh pr merge --auto -m "$PR_URL"
        env:
          PR_URL: ${{github.event.pull_request.html_url}}
          GH_TOKEN: ${{secrets.GITHUB_TOKEN}}
